RIGHTS_CODE_LIST = {
    'ReadArticle': 0,
    'ReadAllArticle': 1,
    'AddArticle': 2,
    'AddAllArticle': 3,
    'ChangeArticle': 4,
    'ChangeAllArticle': 5,
    'DeleteArticle': 6,
    'DeleteAllArticle': 7,
    'AddArticleTag': 8,
    'AddAllArticleTag': 9,
    'ChangeArticleTag': 10,
    'ChangeAllArticleTag': 11,
    'AddComment': 12,
    'AddAllComment': 13,
    'AddCommentByTag': 14,
    'AddNotice': 15,
    'ChangeNotice': 16,
    'DeleteNotice': 17,
    'RightControl': 18,
}
